### ISSUE TITLE
Banks.list()

### ISSUE THREAD

**Issue by lucasferreiraestevam** [rodgeraraujo/juno-api#1]
this lib works in sandbox ? i call function banks.list() and returns (Cannot read property 'list' of undefined)[](url)
![Captura de Tela 2021-03-08 às 12 30 41](https://user-images.githubusercontent.com/12140708/110342778-8edfec00-800a-11eb-9b02-2cdac9027816.png)

**Comment by lucasferreiraestevam** [comment]
@rodgeraraujo

**Comment by rodgeraraujo** [comment]
Hi, can you share a reproduction? Or how you make the use of the lib? I just performed a test, and everything is fine, see bellow.

```js
const RESOURCE_TOKEN = 'YOUR-RESOURCE-TOKEN';
const CLIENT_ID = 'YOUR-CLIENT-ID';
const CLIENT_SECRET = 'YOUR-CLIENT-SECRET';

const Juno = require('juno-api');

const auth = new Juno({
	clientId: CLIENT_ID,
	clientSecret: CLIENT_SECRET,
	isProd: false
});

const accessToken = await auth.authorization.accessToken();

const juno = new Juno({
	accessToken: accessToken.access_token,
	resourceToken: RESOURCE_TOKEN,
	isProd: false
});

const banks =  await juno.bank.list();
console.log(banks)
// log
{
	_embedded: {
		banks: [
		...
		]
	},
	_links: {
		self: {
		href: 'https://sandbox.boletobancario.com/api-integration/data/banks'
		}
	}
}
```

**Comment by lucasferreiraestevam** [comment]
Service Example : https://jsfiddle.net/lucasferreiraestevam/fsm12dpe/#&togetherjs=Fz7cQAAM2g

I change juno.banks.list() -> to -> juno.bank.list(); and now returns 

 {
  "name": "HTTPError"
}

**Comment by lucasferreiraestevam** [comment]
@rodgeraraujo , I found problem, as I made the store of access_token in the database, I did not pay attention to the length of the string, that was just the problem. thanks

**Comment by rodgeraraujo** [comment]
@lucasferreiraestevam I went through the least problem, when I saw that you had also saved the same in the bank. You are welcome, any problem or doubt just open a new issue.

**Comment by lucasferreiraestevam** [comment]
@rodgeraraujo thanks  \m/
