### ISSUE TITLE
create creditCardToken está undefined

### ISSUE THREAD

**Issue by Renan04lima** [rodgeraraujo/juno-api#11]
Olá, alguém sabe o que pode tá causando esse undefined quando tento tokenizar um cartão de crédito? ou como faço pra descobrir o que tá dando errado? 

![juno-tokenizar-erro](https://user-images.githubusercontent.com/48491038/123147688-b762e900-d435-11eb-9dc3-847db3931dc0.png)

**Comment by rodgeraraujo** [comment]
@Renan04lima consegue fazer um log do que tem dentro da instância do `juno`?

**Comment by Renan04lima** [comment]
aqui tá o log

![issue-jono-token](https://user-images.githubusercontent.com/48491038/123437057-a76a1700-d5a5-11eb-853e-c58f3fde2c62.png)


> @Renan04lima consegue fazer um log do que tem dentro da instância do `juno`?

**Comment by rodgeraraujo** [comment]
@Renan04lima Ah, encontrei o problema.

```
creditCard: {};
creditCardToken: {
    create: (params: Juno.ICreateCreditCardToken) => Promise<Juno.ITokenizedCreditCard>;
};
```

Erro na tipagem, o certo é somente `creditCard` e não `creditCardToken`. O objeto `creditCardToken` não existe por isso causa undefined.

**Comment by Renan04lima** [comment]
@rodgeraraujo tentei aqui denovo, mas não deu certo... se não for pedi muito, você tem algum exemplo de como usar o `juno.creditCard`? olhei o código da lib e vi que o `CreditCardToken` criar uma instância e o `CreditCard` tokenizar, mas mesmo assim não sei usar.

nessa imagem tá o console.error no catch de umas das tentivas que fiz

![juno-issues-2](https://user-images.githubusercontent.com/48491038/123469323-45230d80-d5c9-11eb-8d5f-3abd0f8fb95c.png)
