### ISSUE TITLE
Any way to debug the error return of the api?

### ISSUE THREAD

**Issue by lucasferreiraestevam** [rodgeraraujo/juno-api#2]
The **GOT** http client used in lib, only returns "HttpError"

![Captura de Tela 2021-03-08 às 16 10 58](https://user-images.githubusercontent.com/12140708/110370481-7bdd1400-802a-11eb-9e75-ac68fe6bb315.png)

@rodgeraraujo

**Comment by lucasferreiraestevam** [comment]
catch (e) {
      return e.response.body
}

solved!

**Comment by rodgeraraujo** [comment]
@lucasferreiraestevam 
> catch (e) {
> return e.response.body
> }
> 
> solved!

Using try/catch works too, you can use catch to return the error in the best possible way, but you can do this too

```js
const response = await juno.digitalAccountcreate(data).catch((err) => err.response.body);
```

This way, always response return the Juno response object data.
