### ISSUE TITLE
Recurso para Transferências

### ISSUE THREAD

**Issue by lucasferreiraestevam** [rodgeraraujo/juno-api#4]
@rodgeraraujo  firme ? pra eu criar um recurso de transferências é somente eu fazer isso aqui msm ?
![Captura de Tela 2021-04-08 às 11 26 12](https://user-images.githubusercontent.com/12140708/114044234-6ba09a80-985d-11eb-8c5f-db23c2768ea3.png)

**Comment by lucasferreiraestevam** [comment]
@rodgeraraujo implementei aqui e é isso msm, vou fazer um fork do projeto e subo um pull request, posso contribuir ?

**Comment by rodgeraraujo** [comment]
@lucasferreiraestevam pode ficar a vontade pra contribuir com o projeto! Caso pretenda contribuir novamente, adicionar types no arquivo index.d.ts, além de efetuar criação de testes pra o recurso criado. Obrigado por contribuir.
