### ISSUE TITLE
Como importar no Typescript

### ISSUE THREAD

**Issue by GuilhermeCunha** [rodgeraraujo/juno-api#7]
Todas as formas que tentei de importar a biblioteca acabam importando o namespace, o que não me oferece as tipagens para utilizar a lib. Alguém conseguiria me ajudar com isso ? Muito obrigado !

![image](https://user-images.githubusercontent.com/19752833/118669107-daadcf00-b7cb-11eb-8cc9-cdc719e17bbb.png)

**Comment by GuilhermeCunha** [comment]
![image](https://user-images.githubusercontent.com/19752833/118691110-1ef69a80-b7df-11eb-8046-559b108e2600.png)

**Comment by rodgeraraujo** [comment]
@GuilhermeCunha utilizando com TS realmente tem esse problema, outro rapaz também teve o mesmo problema, só não sei informar como o mesmo foi realizado.

**Comment by rodgeraraujo** [comment]
@GuilhermeCunha pra resolver o problema da importação pode tentar fazer a importação assim:
```javascript
import Juno = require("juno-api")
```

Porém creio que a typagem do options do construtor, esteja com problemas referente aos dados obrigatórios, como pode ver nesse [exemplo](https://codesandbox.io/s/typescript-forked-3pb07?file=/src/index.ts). Caso queira ajustar, pode efetuar um pull request para o mesmo, pode testar editando o `index.d.ts` do pacote instalado na seu projeto.
